name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main

permissions:
  id-token: write # This is required for requesting the JWT

jobs:
  build:
    name: Build Docusaurus
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - uses: pnpm/action-setup@v4
        name: Install pnpm
        with:
          version: 9
          run_install: false

      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 21
          cache: "pnpm"

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Build website
        run: pnpm build

      - name: Upload Build Artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: build

  deploy:
    name: Deploy to S3
    needs: build

    permissions

    runs-on: ubuntu-latest
    steps:
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          managed-session-policies: arn:aws:iam::aws:policy/AmazonS3FullAccess
          aws-region: eu-north-1
      - name: Upload to s3
        run: aws s3 sync ./.docusaurus s3://prometheux-docs
      - name: Invalidate cloudfront
        run: |-
          aws cloudfront create-invalidation \
            --distribution-id E9X11W9SXSFDG \
            --paths "/*"
